# TCL File Generated by Component Editor 17.0
# Tue Nov 18 14:10:10 PST 2025
# DO NOT MODIFY


# 
# custom_fpga_reg "c_f_reg" v1.0
#  2025.11.18.14:10:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module custom_fpga_reg
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_fpga_reg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "custom logic"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME c_f_reg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fpga_registers
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fpga_register.v VERILOG PATH soc_system/synthesis/custom/fpga_register.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avs_0
# 
add_interface avs_0 avalon end
set_interface_property avs_0 addressUnits WORDS
set_interface_property avs_0 associatedClock clock
set_interface_property avs_0 associatedReset reset
set_interface_property avs_0 bitsPerSymbol 8
set_interface_property avs_0 burstOnBurstBoundariesOnly false
set_interface_property avs_0 burstcountUnits WORDS
set_interface_property avs_0 explicitAddressSpan 0
set_interface_property avs_0 holdTime 0
set_interface_property avs_0 linewrapBursts false
set_interface_property avs_0 maximumPendingReadTransactions 0
set_interface_property avs_0 maximumPendingWriteTransactions 0
set_interface_property avs_0 readLatency 0
set_interface_property avs_0 readWaitTime 1
set_interface_property avs_0 setupTime 0
set_interface_property avs_0 timingUnits Cycles
set_interface_property avs_0 writeWaitTime 0
set_interface_property avs_0 ENABLED true
set_interface_property avs_0 EXPORT_OF ""
set_interface_property avs_0 PORT_NAME_MAP ""
set_interface_property avs_0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_0 SVD_ADDRESS_GROUP ""

add_interface_port avs_0 avs_address address Input 2
add_interface_port avs_0 avs_chipselect chipselect Input 1
add_interface_port avs_0 avs_write_n write_n Input 1
add_interface_port avs_0 avs_writedata writedata Input 32
add_interface_port avs_0 avs_readdata readdata Output 32
set_interface_assignment avs_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_0 embeddedsw.configuration.isPrintableDevice 0

