# TCL File Generated by Component Editor 17.0
# Mon Jan 26 18:06:10 PST 2026
# DO NOT MODIFY


# 
# fpga_data_source "f_dat_src" v1.0
#  2026.01.26.18:06:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fpga_data_source
# 
set_module_property DESCRIPTION ""
set_module_property NAME fpga_data_source
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "custom logic"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME f_dat_src
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fpga_data_source
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fpga_data_source.v VERILOG PATH soc_system/synthesis/custom/fpga_data_source.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 12 ""
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH DESCRIPTION ""
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter STRB_WIDTH INTEGER 4
set_parameter_property STRB_WIDTH DEFAULT_VALUE 4
set_parameter_property STRB_WIDTH DISPLAY_NAME STRB_WIDTH
set_parameter_property STRB_WIDTH TYPE INTEGER
set_parameter_property STRB_WIDTH UNITS None
set_parameter_property STRB_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property STRB_WIDTH HDL_PARAMETER true
add_parameter ID_WIDTH INTEGER 14 ""
set_parameter_property ID_WIDTH DEFAULT_VALUE 14
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH TYPE INTEGER
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ID_WIDTH DESCRIPTION ""
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter AWUSER_ENABLE INTEGER 0
set_parameter_property AWUSER_ENABLE DEFAULT_VALUE 0
set_parameter_property AWUSER_ENABLE DISPLAY_NAME AWUSER_ENABLE
set_parameter_property AWUSER_ENABLE TYPE INTEGER
set_parameter_property AWUSER_ENABLE UNITS None
set_parameter_property AWUSER_ENABLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWUSER_ENABLE HDL_PARAMETER true
add_parameter AWUSER_WIDTH INTEGER 1
set_parameter_property AWUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property AWUSER_WIDTH DISPLAY_NAME AWUSER_WIDTH
set_parameter_property AWUSER_WIDTH TYPE INTEGER
set_parameter_property AWUSER_WIDTH UNITS None
set_parameter_property AWUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWUSER_WIDTH HDL_PARAMETER true
add_parameter WUSER_ENABLE INTEGER 0
set_parameter_property WUSER_ENABLE DEFAULT_VALUE 0
set_parameter_property WUSER_ENABLE DISPLAY_NAME WUSER_ENABLE
set_parameter_property WUSER_ENABLE TYPE INTEGER
set_parameter_property WUSER_ENABLE UNITS None
set_parameter_property WUSER_ENABLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WUSER_ENABLE HDL_PARAMETER true
add_parameter WUSER_WIDTH INTEGER 1
set_parameter_property WUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property WUSER_WIDTH DISPLAY_NAME WUSER_WIDTH
set_parameter_property WUSER_WIDTH TYPE INTEGER
set_parameter_property WUSER_WIDTH UNITS None
set_parameter_property WUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WUSER_WIDTH HDL_PARAMETER true
add_parameter BUSER_ENABLE INTEGER 0
set_parameter_property BUSER_ENABLE DEFAULT_VALUE 0
set_parameter_property BUSER_ENABLE DISPLAY_NAME BUSER_ENABLE
set_parameter_property BUSER_ENABLE TYPE INTEGER
set_parameter_property BUSER_ENABLE UNITS None
set_parameter_property BUSER_ENABLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUSER_ENABLE HDL_PARAMETER true
add_parameter BUSER_WIDTH INTEGER 1
set_parameter_property BUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property BUSER_WIDTH DISPLAY_NAME BUSER_WIDTH
set_parameter_property BUSER_WIDTH TYPE INTEGER
set_parameter_property BUSER_WIDTH UNITS None
set_parameter_property BUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUSER_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point axi4stream_master
# 
add_interface axi4stream_master axi4stream start
set_interface_property axi4stream_master associatedClock clock
set_interface_property axi4stream_master associatedReset reset
set_interface_property axi4stream_master ENABLED true
set_interface_property axi4stream_master EXPORT_OF ""
set_interface_property axi4stream_master PORT_NAME_MAP ""
set_interface_property axi4stream_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_master axis4_m_tdata tdata Output 8
add_interface_port axi4stream_master axis4_m_tvalid tvalid Output 1
add_interface_port axi4stream_master axis4_m_tready tready Input 1
add_interface_port axi4stream_master axis4_m_tlast tlast Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_readdata readdata Output 32
add_interface_port avalon_slave avs_address address Input 2
add_interface_port avalon_slave avs_chipselect chipselect Input 1
add_interface_port avalon_slave avs_write_n write_n Input 1
add_interface_port avalon_slave avs_writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock ""
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit dma_ack dma_ack Input 1
add_interface_port conduit dma_req dma_req Output 1
add_interface_port conduit dma_single dma_single Output 1


# 
# connection point altera_axi_slave
# 
add_interface altera_axi_slave axi end
set_interface_property altera_axi_slave associatedClock clock
set_interface_property altera_axi_slave associatedReset reset
set_interface_property altera_axi_slave readAcceptanceCapability 1
set_interface_property altera_axi_slave writeAcceptanceCapability 1
set_interface_property altera_axi_slave combinedAcceptanceCapability 1
set_interface_property altera_axi_slave readDataReorderingDepth 1
set_interface_property altera_axi_slave bridgesToMaster ""
set_interface_property altera_axi_slave ENABLED true
set_interface_property altera_axi_slave EXPORT_OF ""
set_interface_property altera_axi_slave PORT_NAME_MAP ""
set_interface_property altera_axi_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi_slave axi_awid awid Input ID_WIDTH
add_interface_port altera_axi_slave axi_awaddr awaddr Input ADDR_WIDTH
add_interface_port altera_axi_slave axi_awlen awlen Input 4
add_interface_port altera_axi_slave axi_awsize awsize Input 3
add_interface_port altera_axi_slave axi_awburst awburst Input 2
add_interface_port altera_axi_slave axi_awcache awcache Input 4
add_interface_port altera_axi_slave axi_awprot awprot Input 3
add_interface_port altera_axi_slave axi_awuser awuser Input AWUSER_WIDTH
add_interface_port altera_axi_slave axi_awvalid awvalid Input 1
add_interface_port altera_axi_slave axi_awready awready Output 1
add_interface_port altera_axi_slave axi_awlock awlock Input 2
add_interface_port altera_axi_slave axi_wdata wdata Input DATA_WIDTH
add_interface_port altera_axi_slave axi_wstrb wstrb Input STRB_WIDTH
add_interface_port altera_axi_slave axi_wlast wlast Input 1
add_interface_port altera_axi_slave axi_wvalid wvalid Input 1
add_interface_port altera_axi_slave axi_wready wready Output 1
add_interface_port altera_axi_slave axi_wid wid Input ID_WIDTH
add_interface_port altera_axi_slave axi_bid bid Output ID_WIDTH
add_interface_port altera_axi_slave axi_bresp bresp Output 2
add_interface_port altera_axi_slave axi_bvalid bvalid Output 1
add_interface_port altera_axi_slave axi_bready bready Input 1
add_interface_port altera_axi_slave axi_arid arid Input ID_WIDTH
add_interface_port altera_axi_slave axi_araddr araddr Input ADDR_WIDTH
add_interface_port altera_axi_slave axi_arlen arlen Input 4
add_interface_port altera_axi_slave axi_arsize arsize Input 3
add_interface_port altera_axi_slave axi_arburst arburst Input 2
add_interface_port altera_axi_slave axi_arcache arcache Input 4
add_interface_port altera_axi_slave axi_arprot arprot Input 3
add_interface_port altera_axi_slave axi_arvalid arvalid Input 1
add_interface_port altera_axi_slave axi_arready arready Output 1
add_interface_port altera_axi_slave axi_arlock arlock Input 2
add_interface_port altera_axi_slave axi_rid rid Output ID_WIDTH
add_interface_port altera_axi_slave axi_rdata rdata Output DATA_WIDTH
add_interface_port altera_axi_slave axi_rresp rresp Output 2
add_interface_port altera_axi_slave axi_rlast rlast Output 1
add_interface_port altera_axi_slave axi_rvalid rvalid Output 1
add_interface_port altera_axi_slave axi_rready rready Input 1

