# TCL File Generated by Component Editor 17.0
# Sat Nov 22 15:16:15 PST 2025
# DO NOT MODIFY


# 
# dsp_apb "dsp_apb_slave" v1.0
#  2025.11.22.15:16:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dsp_apb
# 
set_module_property DESCRIPTION ""
set_module_property NAME dsp_apb
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "custom logic"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dsp_apb_slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fpga_dsp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fpga_dsp.v VERILOG PATH soc_system/synthesis/custom/fpga_dsp.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset_if
# 
add_interface reset_if reset end
set_interface_property reset_if associatedClock clock
set_interface_property reset_if synchronousEdges DEASSERT
set_interface_property reset_if ENABLED true
set_interface_property reset_if EXPORT_OF ""
set_interface_property reset_if PORT_NAME_MAP ""
set_interface_property reset_if CMSIS_SVD_VARIABLES ""
set_interface_property reset_if SVD_ADDRESS_GROUP ""

add_interface_port reset_if rstn reset_n Input 1


# 
# connection point apb_slave_if
# 
add_interface apb_slave_if apb end
set_interface_property apb_slave_if associatedClock clock
set_interface_property apb_slave_if associatedReset reset_if
set_interface_property apb_slave_if ENABLED true
set_interface_property apb_slave_if EXPORT_OF ""
set_interface_property apb_slave_if PORT_NAME_MAP ""
set_interface_property apb_slave_if CMSIS_SVD_VARIABLES ""
set_interface_property apb_slave_if SVD_ADDRESS_GROUP ""

add_interface_port apb_slave_if apb_slave_paddr paddr Input 4
add_interface_port apb_slave_if apb_slave_penable penable Input 1
add_interface_port apb_slave_if apb_slave_prdata prdata Output 32
add_interface_port apb_slave_if apb_slave_pwdata pwdata Input 32
add_interface_port apb_slave_if apb_slave_pwrite pwrite Input 1
add_interface_port apb_slave_if apb_slave_psel psel Input 1
add_interface_port apb_slave_if apb_slave_pready pready Output 1


# 
# connection point axi4stream_master_if
# 
add_interface axi4stream_master_if axi4stream start
set_interface_property axi4stream_master_if associatedClock clock
set_interface_property axi4stream_master_if associatedReset reset_if
set_interface_property axi4stream_master_if ENABLED true
set_interface_property axi4stream_master_if EXPORT_OF ""
set_interface_property axi4stream_master_if PORT_NAME_MAP ""
set_interface_property axi4stream_master_if CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master_if SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_master_if axis4_m_tdata tdata Output 8
add_interface_port axi4stream_master_if axis4_m_tready tready Input 1
add_interface_port axi4stream_master_if axis4_m_tvalid tvalid Output 1
add_interface_port axi4stream_master_if axis4_m_tlast tlast Output 1


# 
# connection point axi4stream_slave_if
# 
add_interface axi4stream_slave_if axi4stream end
set_interface_property axi4stream_slave_if associatedClock clock
set_interface_property axi4stream_slave_if associatedReset reset_if
set_interface_property axi4stream_slave_if ENABLED true
set_interface_property axi4stream_slave_if EXPORT_OF ""
set_interface_property axi4stream_slave_if PORT_NAME_MAP ""
set_interface_property axi4stream_slave_if CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_slave_if SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_slave_if axis4_s_tdata tdata Input 8
add_interface_port axi4stream_slave_if axis4_s_tready tready Output 1
add_interface_port axi4stream_slave_if axis4_s_tvalid tvalid Input 1
add_interface_port axi4stream_slave_if axis4_s_tlast tlast Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

